name:                keep-talking-password-solver
version:             0.1.0.0
github:              "githubuser/keep-talking-password-solver"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/keep-talking-password-solver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ktane-password-full:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keep-talking-password-solver

  ktane-password-three:
    main:                Three.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Three
    dependencies:
    - keep-talking-password-solver

tests:
  keep-talking-password-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - keep-talking-password-solver
